### Student Marks Analysis

In [ ]:
#Problem Statement

#You are given marks of 5 students in 4 subjects.
#Use NumPy to analyze the data.

In [1]:
import numpy as np

marks = np.array([[78, 85, 90, 88],
                  [92, 80, 75, 85],
                  [65, 70, 72, 68],
                  [88, 90, 92, 91],
                  [70, 75, 78, 74]])

In [ ]:
# Task 1

#Find the total marks of each student.

In [9]:
marks.sum(axis=1)

array([341, 332, 275, 361, 297])

In [ ]:
#Task 2

#Find the average marks of each subject.

In [12]:
marks.mean(axis=0)

array([78.6, 80. , 81.4, 81.2])

In [ ]:
# Task 3

#Find the highest marks in each subject.

In [13]:
marks.max(axis=0)

array([92, 90, 92, 91])

In [ ]:
# Task 4

#Find the student who scored highest total marks

In [16]:
total = marks.sum(axis=1)
total.argmax()

np.int64(3)

In [ ]:
# Task 5

#Add 5 grace marks to all students using broadcasting.

In [19]:
marks+5

array([[83, 90, 95, 93],
       [97, 85, 80, 90],
       [70, 75, 77, 73],
       [93, 95, 97, 96],
       [75, 80, 83, 79]])

In [ ]:
# Task 6

#Reshape the array into 10 × 2 (if possible).

In [20]:
marks.reshape(10,2)

array([[78, 85],
       [90, 88],
       [92, 80],
       [75, 85],
       [65, 70],
       [72, 68],
       [88, 90],
       [92, 91],
       [70, 75],
       [78, 74]])

### Sales Data Analysis

In [21]:
# You are given weekly sales data of 4 stores for 7 days.

In [23]:
sales = np.array([[200, 220, 250, 230, 240, 260, 270],
                  [180, 190, 200, 210, 205, 215, 220],
                  [300, 310, 320, 330, 340, 350, 360],
                  [150, 160, 170, 165, 175, 180, 185]])

#Rows -> stores
#column -> Days

In [24]:
# 1️⃣ Total weekly sales of each store

sales.sum(axis=1)

array([1670, 1420, 2310, 1185])

In [27]:
# 2️⃣ Average daily sales across all stores

sales.mean(axis = 0)

array([207.5 , 220.  , 235.  , 233.75, 240.  , 251.25, 258.75])

In [29]:
# 3️⃣ Highest sales recorded in the week

sales.max()

np.int64(360)

In [34]:
# 4️⃣ Store with lowest total sales

totals=sales.sum(axis=1)
totals.argmin()

np.int64(3)

In [37]:
# 5️⃣ Increase all sales by 10% using broadcasting

new_sales = sales*1.10
print(new_sales)

[[220.  242.  275.  253.  264.  286.  297. ]
 [198.  209.  220.  231.  225.5 236.5 242. ]
 [330.  341.  352.  363.  374.  385.  396. ]
 [165.  176.  187.  181.5 192.5 198.  203.5]]


In [40]:
# 6️⃣ Find sales greater than 300

sales[sales>300]

array([310, 320, 330, 340, 350, 360])

### Temperature Analysis

In [ ]:
# You are given temperature (°C) of 6 cities recorded for 5 days.

In [41]:
import numpy as np

temp = np.array([[30, 32, 31, 29, 28],
                 [35, 36, 34, 33, 32],
                 [25, 27, 26, 24, 23],
                 [40, 42, 41, 39, 38],
                 [20, 22, 21, 19, 18],
                 [33, 34, 35, 36, 37]])
# Rows -> cities(6)
# columns -> Days(5)

In [42]:
#1️⃣ Find average temperature of each city

temp.mean(axis=1)

array([30., 34., 25., 40., 20., 35.])

In [44]:
#2️⃣ Find hottest day (day with highest average temperature across cities)

#(Hint: first find column-wise mean, then argmax)

hottest = temp.mean(axis=0)
hottest.argmax()

np.int64(1)

In [46]:
#3️⃣ Find city with lowest minimum temperature

#(Hint: first find row-wise min, then argmin)

lowest_temp =temp.min(axis=0)
lowest_temp.argmin()

np.int64(4)

In [52]:
#4️⃣ Increase temperature of city 3 by 2 degrees (only city 3)

temp[2]+2

array([27, 29, 28, 26, 25])

In [56]:
#5️⃣ Convert all temperatures from Celsius to Fahrenheit

#Formula:

#F = (C × 9/5) + 32

f=temp.copy()
f = (temp * 9/5)+32
f

array([[ 86. ,  89.6,  87.8,  84.2,  82.4],
       [ 95. ,  96.8,  93.2,  91.4,  89.6],
       [ 77. ,  80.6,  78.8,  75.2,  73.4],
       [104. , 107.6, 105.8, 102.2, 100.4],
       [ 68. ,  71.6,  69.8,  66.2,  64.4],
       [ 91.4,  93.2,  95. ,  96.8,  98.6]])

In [57]:
#6️⃣ Find all temperatures above 35°C

temp[temp > 35]

array([36, 40, 42, 41, 39, 38, 36, 37])

### Employee Salary Analysis

You are given monthly salaries (₹) of 6 employees for 5 months.

In [81]:
import numpy as np

salary = np.array([[30000, 32000, 31000, 33000, 34000],
                   [28000, 29000, 30000, 31000, 32000],
                   [40000, 42000, 41000, 43000, 44000],
                   [25000, 26000, 27000, 28000, 29000],
                   [35000, 36000, 37000, 38000, 39000],
                   [22000, 23000, 24000, 25000, 26000]])

#Rows → Employees
#Columns → Months

In [82]:
#1️⃣ Total salary of each employee

total = salary.sum(axis=1)
total

array([160000, 150000, 210000, 135000, 185000, 120000])

In [83]:
#2️⃣ Average salary of each month
salary.mean(axis=0)

array([30000.        , 31333.33333333, 31666.66666667, 33000.        ,
       34000.        ])

In [84]:
#3️⃣ Employee with highest total salary
total = salary.sum(axis=1)
total

array([160000, 150000, 210000, 135000, 185000, 120000])

In [85]:
#4️⃣ Increase salary of employee 2 by 15%

salary[1] = salary[1] * 1.15
salary[1]

array([32199, 33350, 34500, 35650, 36800])

In [88]:
#5️⃣ Find salaries greater than 40,000
salary[salary > 40000]

array([42000, 41000, 43000, 44000])

In [89]:
#6️⃣ Reshape salary data into 10 × 3 (check if possible)
salary.reshape(10,3)

array([[30000, 32000, 31000],
       [33000, 34000, 32199],
       [33350, 34500, 35650],
       [36800, 40000, 42000],
       [41000, 43000, 44000],
       [25000, 26000, 27000],
       [28000, 29000, 35000],
       [36000, 37000, 38000],
       [39000, 22000, 23000],
       [24000, 25000, 26000]])

### sales dataset
 Monthly sales (in ₹) of 5 stores over 6 months

In [94]:
import numpy as np

# Monthly sales (in ₹) of 5 stores over 6 months
sales = np.array([
    [200, 220, 250, 230, 210, 240],
    [150, 180, 200, 170, 160, 190],
    [300, 320, 310, 330, 340, 350],
    [100, 120, 110, 130, 140, 150],
    [250, 270, 260, 280, 290, 300]
])


In [97]:
#1️⃣ Array Basics

#Find the shape and size of the array
sales.shape
sales.size
#Find dtype of the array
print(type(sales))

<class 'numpy.ndarray'>


In [110]:
# 2️⃣ Indexing & Slicing

#Print sales of store 3
sales[2]
#Print sales of the first 3 stores for first 4 months
sales[:3,:4]
#Print sales for last 2 stores and last 3 months
sales[-2:,-3:]

array([[130, 140, 150],
       [280, 290, 300]])

In [117]:
# 3️⃣ Aggregation

#Find total sales of each store (row-wise sum)
total = sales.sum(axis=1)
total
#Find total sales of each month (column-wise sum)
total_sales = sales.sum(axis=0)
total_sales
#Find maximum sale overall
sales.max()
#Find minimum sale for each store
sales.min()
#Find average sale for each store
sales.mean()

np.float64(225.0)

In [132]:
# 4️⃣ Broadcasting

#Increase all sales by 10%
new_sales = sales*1.10
print(new_sales)
#Give bonus ₹50 to sales above 300
bonus_sales = sales.copy()
bonus_sales[bonus_sales > 300] +=50
print(bonus_sales)

[[220. 242. 275. 253. 231. 264.]
 [165. 198. 220. 187. 176. 209.]
 [330. 352. 341. 363. 374. 385.]
 [110. 132. 121. 143. 154. 165.]
 [275. 297. 286. 308. 319. 330.]]
[[200 220 250 230 210 240]
 [150 180 200 170 160 190]
 [300 370 360 380 390 400]
 [100 120 110 130 140 150]
 [250 270 260 280 290 300]]


In [141]:
# 5️⃣ Random & Other Functions

#Generate a 3×3 random array of integers between 1–50
arr = np.random.randint(1,51,(3,3))
print(arr)
#Reshape the sales array into 6×5
sales.reshape(6,5)
#Transpose the sales array
sales.transpose()

[[11 22 31]
 [13 13  1]
 [ 8 32 15]]


array([[200, 150, 300, 100, 250],
       [220, 180, 320, 120, 270],
       [250, 200, 310, 110, 260],
       [230, 170, 330, 130, 280],
       [210, 160, 340, 140, 290],
       [240, 190, 350, 150, 300]])

In [145]:
# 6️⃣ Boolean Indexing

#Print all sales above 250
sales[sales>250]
#Print stores that had any month with sales < 150
low_sales = sales[(sales < 150).any(axis=1)]
print(low_sales)

[[100 120 110 130 140 150]]
