In [1]:
import numpy as np

In [2]:
a1 = np.array([20,40,50,70])

In [3]:
a2 = np.array([[20,40,50,70],[10,30,50,80],[5,20,50,70]])
a2

array([[20, 40, 50, 70],
       [10, 30, 50, 80],
       [ 5, 20, 50, 70]])

In [4]:
a2.shape

(3, 4)

In [5]:
a2.size

12

In [6]:
a3 = np.array([[[20,40,50,70],[10,30,50,80],[5,20,50,70]],
                    [[20,40,50,70],[10,30,50,80],[5,20,50,70]]])
a3

array([[[20, 40, 50, 70],
        [10, 30, 50, 80],
        [ 5, 20, 50, 70]],

       [[20, 40, 50, 70],
        [10, 30, 50, 80],
        [ 5, 20, 50, 70]]])

In [7]:
a3.shape

(2, 3, 4)

In [8]:
## create numpy arrays from inbuild methods.
# zeros,ones,full,diag,identity......
# arange,linespace......
# random

In [9]:
np.zeros((5,10), dtype="int8") # By default zeros are float so convert it into int.

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [10]:
np.ones((5,10), dtype='int8')

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

In [11]:
np.full((5,10),5) # in full method we need to fill the value here. which value you want to fill

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [12]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
l1=[1,2,3,4]

In [14]:
np.diag(l1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [15]:
np.diag(l1,-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [16]:
a4=np.arange(0,10.5,0.5) # start,end,step (basically this is the combination of array + range = arange)

In [17]:
a5=np.linspace(1,20,50) #start-> starting value,stop->ending value,num->how many number you want.
                    # This function generates equally spaced numbers within a given range.

In [18]:
a6=np.random.random(10)

In [19]:
np.random.randint(10) 

5

In [20]:
a7=np.random.randint(10,100,100)

In [21]:
a6.reshape((2,5))
a6.reshape((5,2))
a6.reshape((1,10))
a6.reshape((10,1))

# They should be same

array([[0.72106286],
       [0.59947184],
       [0.4636386 ],
       [0.59413347],
       [0.32776197],
       [0.68863286],
       [0.72933888],
       [0.64879321],
       [0.09334856],
       [0.59828072]])

In [22]:
a2

array([[20, 40, 50, 70],
       [10, 30, 50, 80],
       [ 5, 20, 50, 70]])

In [23]:
a2.transpose() # convert 1st dimension to 2nd dimension,2nd dimension to 1st dimension.

array([[20, 10,  5],
       [40, 30, 20],
       [50, 50, 50],
       [70, 80, 70]])

In [24]:
 a1

array([20, 40, 50, 70])

In [25]:
a1[1]

np.int64(40)

In [26]:
a1[1:3]

array([40, 50])

In [27]:
a1[-1]

np.int64(70)

In [28]:
a2

array([[20, 40, 50, 70],
       [10, 30, 50, 80],
       [ 5, 20, 50, 70]])

### Access The Elements

In [29]:
a2[::]
a2[::,::]

array([[20, 40, 50, 70],
       [10, 30, 50, 80],
       [ 5, 20, 50, 70]])

In [30]:
a2[::,1]

array([40, 30, 20])

In [31]:
a2[1,::]

array([10, 30, 50, 80])

In [32]:
a2[0:2, 1:3]

array([[40, 50],
       [30, 50]])

In [33]:
a2[:,1:3]

array([[40, 50],
       [30, 50],
       [20, 50]])

In [34]:
a2[:,2:4]

array([[50, 70],
       [50, 80],
       [50, 70]])

In [35]:
a2[:2,:2]

array([[20, 40],
       [10, 30]])

In [36]:
a2[-1:-5:-1]

array([[ 5, 20, 50, 70],
       [10, 30, 50, 80],
       [20, 40, 50, 70]])

### Update the Elements

In [37]:
a2

array([[20, 40, 50, 70],
       [10, 30, 50, 80],
       [ 5, 20, 50, 70]])

In [38]:
a2[:2,2:]=100

In [39]:
a2

array([[ 20,  40, 100, 100],
       [ 10,  30, 100, 100],
       [  5,  20,  50,  70]])

In [40]:
a7

array([39, 60, 21, 72, 25, 39, 45, 77, 55, 11, 51, 50, 43, 51, 86, 89, 81,
       83, 61, 74, 11, 13, 90, 20, 30, 25, 36, 84, 77, 13, 40, 76, 82, 14,
       10, 20, 25, 59, 29, 36, 24, 82, 45, 82, 60, 50, 84, 81, 12, 23, 62,
       47, 42, 60, 81, 82, 19, 91, 48, 15, 39, 65, 44, 72, 70, 97, 15, 71,
       89, 52, 78, 82, 73, 47, 61, 25, 65, 82, 17, 86, 20, 33, 49, 13, 82,
       13, 63, 82, 56, 18, 28, 67, 41, 15, 88, 15, 99, 43, 58, 36],
      dtype=int32)

In [41]:
a7.shape

(100,)

In [42]:
a7.reshape((10,10))

array([[39, 60, 21, 72, 25, 39, 45, 77, 55, 11],
       [51, 50, 43, 51, 86, 89, 81, 83, 61, 74],
       [11, 13, 90, 20, 30, 25, 36, 84, 77, 13],
       [40, 76, 82, 14, 10, 20, 25, 59, 29, 36],
       [24, 82, 45, 82, 60, 50, 84, 81, 12, 23],
       [62, 47, 42, 60, 81, 82, 19, 91, 48, 15],
       [39, 65, 44, 72, 70, 97, 15, 71, 89, 52],
       [78, 82, 73, 47, 61, 25, 65, 82, 17, 86],
       [20, 33, 49, 13, 82, 13, 63, 82, 56, 18],
       [28, 67, 41, 15, 88, 15, 99, 43, 58, 36]], dtype=int32)

In [43]:
a7+100

array([139, 160, 121, 172, 125, 139, 145, 177, 155, 111, 151, 150, 143,
       151, 186, 189, 181, 183, 161, 174, 111, 113, 190, 120, 130, 125,
       136, 184, 177, 113, 140, 176, 182, 114, 110, 120, 125, 159, 129,
       136, 124, 182, 145, 182, 160, 150, 184, 181, 112, 123, 162, 147,
       142, 160, 181, 182, 119, 191, 148, 115, 139, 165, 144, 172, 170,
       197, 115, 171, 189, 152, 178, 182, 173, 147, 161, 125, 165, 182,
       117, 186, 120, 133, 149, 113, 182, 113, 163, 182, 156, 118, 128,
       167, 141, 115, 188, 115, 199, 143, 158, 136], dtype=int32)

In [44]:
a7/10

array([3.9, 6. , 2.1, 7.2, 2.5, 3.9, 4.5, 7.7, 5.5, 1.1, 5.1, 5. , 4.3,
       5.1, 8.6, 8.9, 8.1, 8.3, 6.1, 7.4, 1.1, 1.3, 9. , 2. , 3. , 2.5,
       3.6, 8.4, 7.7, 1.3, 4. , 7.6, 8.2, 1.4, 1. , 2. , 2.5, 5.9, 2.9,
       3.6, 2.4, 8.2, 4.5, 8.2, 6. , 5. , 8.4, 8.1, 1.2, 2.3, 6.2, 4.7,
       4.2, 6. , 8.1, 8.2, 1.9, 9.1, 4.8, 1.5, 3.9, 6.5, 4.4, 7.2, 7. ,
       9.7, 1.5, 7.1, 8.9, 5.2, 7.8, 8.2, 7.3, 4.7, 6.1, 2.5, 6.5, 8.2,
       1.7, 8.6, 2. , 3.3, 4.9, 1.3, 8.2, 1.3, 6.3, 8.2, 5.6, 1.8, 2.8,
       6.7, 4.1, 1.5, 8.8, 1.5, 9.9, 4.3, 5.8, 3.6])

In [45]:
a7.reshape((10,10))

array([[39, 60, 21, 72, 25, 39, 45, 77, 55, 11],
       [51, 50, 43, 51, 86, 89, 81, 83, 61, 74],
       [11, 13, 90, 20, 30, 25, 36, 84, 77, 13],
       [40, 76, 82, 14, 10, 20, 25, 59, 29, 36],
       [24, 82, 45, 82, 60, 50, 84, 81, 12, 23],
       [62, 47, 42, 60, 81, 82, 19, 91, 48, 15],
       [39, 65, 44, 72, 70, 97, 15, 71, 89, 52],
       [78, 82, 73, 47, 61, 25, 65, 82, 17, 86],
       [20, 33, 49, 13, 82, 13, 63, 82, 56, 18],
       [28, 67, 41, 15, 88, 15, 99, 43, 58, 36]], dtype=int32)

In [46]:
a7>50

array([False,  True, False,  True, False, False, False,  True,  True,
       False,  True, False, False,  True,  True,  True,  True,  True,
        True,  True, False, False,  True, False, False, False, False,
        True,  True, False, False,  True,  True, False, False, False,
       False,  True, False, False, False,  True, False,  True,  True,
       False,  True,  True, False, False,  True, False, False,  True,
        True,  True, False,  True, False, False, False,  True, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True, False,  True, False,
       False, False, False,  True, False,  True,  True,  True, False,
       False,  True, False, False,  True, False,  True, False,  True,
       False])

In [47]:
a7[a7>=50]

array([60, 72, 77, 55, 51, 50, 51, 86, 89, 81, 83, 61, 74, 90, 84, 77, 76,
       82, 59, 82, 82, 60, 50, 84, 81, 62, 60, 81, 82, 91, 65, 72, 70, 97,
       71, 89, 52, 78, 82, 73, 61, 65, 82, 86, 82, 63, 82, 56, 67, 88, 99,
       58], dtype=int32)

In [48]:
a7[a7<90]

array([39, 60, 21, 72, 25, 39, 45, 77, 55, 11, 51, 50, 43, 51, 86, 89, 81,
       83, 61, 74, 11, 13, 20, 30, 25, 36, 84, 77, 13, 40, 76, 82, 14, 10,
       20, 25, 59, 29, 36, 24, 82, 45, 82, 60, 50, 84, 81, 12, 23, 62, 47,
       42, 60, 81, 82, 19, 48, 15, 39, 65, 44, 72, 70, 15, 71, 89, 52, 78,
       82, 73, 47, 61, 25, 65, 82, 17, 86, 20, 33, 49, 13, 82, 13, 63, 82,
       56, 18, 28, 67, 41, 15, 88, 15, 43, 58, 36], dtype=int32)

In [49]:
a7[(a7 >= 50) & (a7 < 90)] # when we have multiple true and false in left hand side and right hand side in that case we bitwise opertor

array([60, 72, 77, 55, 51, 50, 51, 86, 89, 81, 83, 61, 74, 84, 77, 76, 82,
       59, 82, 82, 60, 50, 84, 81, 62, 60, 81, 82, 65, 72, 70, 71, 89, 52,
       78, 82, 73, 61, 65, 82, 86, 82, 63, 82, 56, 67, 88, 58],
      dtype=int32)

In [50]:
a2

array([[ 20,  40, 100, 100],
       [ 10,  30, 100, 100],
       [  5,  20,  50,  70]])

In [51]:
a2 > 70

array([[False, False,  True,  True],
       [False, False,  True,  True],
       [False, False, False, False]])

In [52]:
a2 < 90

array([[ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True,  True,  True]])

In [53]:
a7[(a7 >= 70) & (a7 <= 90)] = 0

In [54]:
a7

array([39, 60, 21,  0, 25, 39, 45,  0, 55, 11, 51, 50, 43, 51,  0,  0,  0,
        0, 61,  0, 11, 13,  0, 20, 30, 25, 36,  0,  0, 13, 40,  0,  0, 14,
       10, 20, 25, 59, 29, 36, 24,  0, 45,  0, 60, 50,  0,  0, 12, 23, 62,
       47, 42, 60,  0,  0, 19, 91, 48, 15, 39, 65, 44,  0,  0, 97, 15,  0,
        0, 52,  0,  0,  0, 47, 61, 25, 65,  0, 17,  0, 20, 33, 49, 13,  0,
       13, 63,  0, 56, 18, 28, 67, 41, 15,  0, 15, 99, 43, 58, 36],
      dtype=int32)

In [55]:
a2

array([[ 20,  40, 100, 100],
       [ 10,  30, 100, 100],
       [  5,  20,  50,  70]])

In [56]:
a2.sum()

np.int64(645)

In [57]:
a2.min()

np.int64(5)

In [58]:
a2.max()

np.int64(100)

In [59]:
a2.sum(axis = 0)

array([ 35,  90, 250, 270])

In [60]:
a2.sum(axis=1)

array([260, 240, 145])

In [61]:
a8 = np.array(range(12)).reshape(4,3)

In [62]:
a9 = np.random.randint(10,100,(4,3))

In [63]:
a8

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [64]:
a9

array([[19, 37, 20],
       [86, 79, 32],
       [45, 37, 25],
       [55, 57, 92]], dtype=int32)

In [65]:
np.hstack((a8,a9))

array([[ 0,  1,  2, 19, 37, 20],
       [ 3,  4,  5, 86, 79, 32],
       [ 6,  7,  8, 45, 37, 25],
       [ 9, 10, 11, 55, 57, 92]])

In [66]:
np.vstack((a8,a9))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [19, 37, 20],
       [86, 79, 32],
       [45, 37, 25],
       [55, 57, 92]])

### PANDAS

In [67]:
pandas provide two data stracture:
1. series : only 1D, Homogenous,one column out of a table is series.
    access:
we can access through[]
[] :
    they will work on user defined indexes when we want to get one value using index.
    work on default indexes when used as slicers.
    in slicers,start till end +/-1 based on step size.
    can be used to filter the record
        
.iloc[] -> access through default index.(Dot(.)iloc)
      they will work on default indexes when we want to get one value using index.
      work on default indexes when used as slicers.
      in slicers,start till end +/-1 based on step size.
      CAN'T be used to filter the record
          
.loc[] -> access through user define index(Dot(.)loc)
       they will work on user defined indexes when we want to get one value using index.
       work on user defined indexes when used as slicers.
       in slicers,start till end.
       can be used to filter the record

.ix[] ->
    they will work on user defined indexes when we want to get one value using index.
    work on default indexes when used as slicers.
    in slicers,start till end +/-1 based on step size.
    can be used to filter the record
    
2. DataFrame: only 2D, hetrogenous, coplete table is DataFrame

numpy already installed with pandas



SyntaxError: invalid decimal literal (3073329252.py, line 2)

In [68]:
import pandas as pd

In [69]:
print(dir(pd.Series))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__bool__', '__class__', '__column_consortium_standard__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__firstlineno__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__',

In [70]:
print(dir(pd.DataFrame))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__dataframe_consortium_standard__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__firstlineno__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__'

In [71]:
print(dir(pd))

['ArrowDtype', 'BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_built_with_meson', '_config', '_is_numpy_dev', '_libs', '_pandas_datetime_CAPI', '_pandas_parser_CAPI', '_testing', '_typing', '_version_meson', 'annotations', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'conca

In [72]:
s1=pd.Series([10,20,30,40,50], dtype='int8',name='col1')

In [73]:
s1

0    10
1    20
2    30
3    40
4    50
Name: col1, dtype: int8

In [74]:
l1=[10,20,30,40,50]

In [75]:
s2=pd.Series(l1,index=range(1,6))

In [76]:
s2

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [77]:
s3=pd.Series(l1, index=['a','b','c','d','e'])

In [78]:
s3

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [79]:
### Access

In [80]:
s1[1]

np.int8(20)

In [81]:
s1[1:4]

1    20
2    30
3    40
Name: col1, dtype: int8

In [82]:
s2

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [83]:
s2[1]

np.int64(10)

In [84]:
s2[2:5] ### slicer is always work on default indexes

3    30
4    40
5    50
dtype: int64

In [85]:
s1[1]

np.int8(20)

In [86]:
s1.iloc[1]

np.int8(20)

In [87]:
s1.loc[1]

np.int8(20)

In [88]:
s1[1:4]

1    20
2    30
3    40
Name: col1, dtype: int8

In [89]:
s1.iloc[1:4]

1    20
2    30
3    40
Name: col1, dtype: int8

In [90]:
s1.loc[1:4]

1    20
2    30
3    40
4    50
Name: col1, dtype: int8

In [91]:
s2

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [92]:
s2[2]

np.int64(20)

In [93]:
s2.iloc[1]

np.int64(20)

In [94]:
s2.loc[2]

np.int64(20)

In [95]:
s2[1:4]

2    20
3    30
4    40
dtype: int64

In [96]:
s2.iloc[1:4]

2    20
3    30
4    40
dtype: int64

In [97]:
s2.loc[2:4]

2    20
3    30
4    40
dtype: int64

In [98]:
s3.loc['a':'c']

a    10
b    20
c    30
dtype: int64

In [99]:
 ### Update (same like numpy (Access the element and update the elemet))

In [100]:
s3.loc['c'] = 300

In [101]:
s3

a     10
b     20
c    300
d     40
e     50
dtype: int64

In [102]:
s4=pd.Series(np.random.randint(10,100,10))

In [103]:
s4

0    44
1    82
2    89
3    59
4    55
5    28
6    57
7    20
8    33
9    49
dtype: int32

In [104]:
s4[(s4 <= 90)]

0    44
1    82
2    89
3    59
4    55
5    28
6    57
7    20
8    33
9    49
dtype: int32

In [105]:
s4.loc[(s4 > 50) & (s4 < 90)]

1    82
2    89
3    59
4    55
6    57
dtype: int32

In [106]:
stores=pd.read_csv(r"C:\Users\rahul\OneDrive\Desktop\stores.csv", sep=',')

In [107]:
type(stores)

pandas.core.frame.DataFrame

In [109]:
Get the Data to work on

Data Understanding/data inspection
     Metadata inspection
     Data inspection

Data cleaning/Data prepration/Data wrangling

     Stracture based changes:
        Subsetting
        Reorder
        Rename
        Drop
        create new column
        Type Conversion

    Content based chnages:
        Sorting
        Filters
        Removal of duplicates

        null/Missing values
        Outliers (Unwanted value)

        Creating group/bins

        Combining the data
            Join/Merge
            Append
            Concat

Summaries:-
    Grouping along with agg function
    Reporting
    charts/Visualization

IndentationError: unindent does not match any outer indentation level (<string>, line 17)